#!/usr/bin/env python3
"""
Process YouTube camera feeds and generate CSV entries with location data
"""

import csv
import re
from datetime import datetime

# Video data extracted from yt-dlp
video_data = [
    ("86-7Dr7yeVQ", "EarthCam Live: New Orleans Balcony View 2025-12-09 21:04", "EarthCam", "https://www.youtube.com/@earthcam/streams"),
    ("2UJDLWcSADk", "Steamboat Square Cam 2025-12-09 21:04", "Steamboat Resort", "https://www.youtube.com/@SteamboatResort/streams"),
    ("XjhxRZEm638", "Leavenworth Washington Live Webcam from Downtown 2025-12-09 21:04", "Visit Leavenworth", "https://www.youtube.com/@VisitLeavenworth/streams"),
    ("dMr-Jt_K3Cc", "Everett's 8800 Cam 2025-12-09 21:04", "Big Sky Resort", "https://www.youtube.com/@BigSkyResort/streams"),
    ("n49L-PpC0Wg", "4k 東京ライブカメラ  @tokyo  live camera  ドコモタワー・左国立競技場・中央新宿御苑・右新宿駅付近・中央奥渋谷。都心通過の着陸機  ＠国立競技場＠東京ライブカメラ＠＃紅葉 2025-12-09 21:04", "Venus117", "https://www.youtube.com/@Venus117/streams"),
    ("9SLt3AT0rXk", "La Grange, Kentucky, USA | Virtual Railfan  LIVE ! 2025-12-09 21:04", "Virtual Railfan", "https://www.youtube.com/@VirtualRailfan/streams"),
    ("TmtVbezZaqg", "Leavenworth Washington Live Webcam from Kris Kringl! 2025-12-09 21:05", "Visit Leavenworth", "https://www.youtube.com/@VisitLeavenworth/streams"),
    ("YuvgiDTzxhU", "Webcam Live San Pellegrino in Alpe (LU) - Garfagnana 2025-12-09 21:05", "Digital Landscapes", "https://www.youtube.com/@DigitalLandscapes/streams"),
    ("ahSMyLJcp48", "서울 실시간 4K 한강 라이브🚗 24/7 SEOUL LIVE 韓國 ソウル ライブカメラ ⛵ 여의도 SEOULDAL 한강버스 63빌딩 서울달 월드컵대교 난지캠핑장 강변북로 DRIVE 2025-12-09 21:05", "RIVERWORKER", "https://www.youtube.com/@RIVERWORKER/streams"),
    ("kC6_JqEt3GA", "MAIN ST. #2 2025-12-09 21:05", "CanmoreAlberta.com", "https://www.youtube.com/@CanmoreAlberta/streams"),
    ("g9Y-Bkq5O0Q", "成田山新勝寺ライブカメラ 2025-12-09 21:05", "NARITASAN SHINSHOJI", "https://www.youtube.com/@naritasan/streams"),
    ("MwcqP3ta6RI", "Calgary Live Camera 2025-12-09 21:05", "DELTATECH Calgary", "https://www.youtube.com/@DeltaTechCalgary/streams"),
    ("wgkdREYOfw0", "Ashland, Virginia, USA  | LIVE RAILCAM - Virtual Railfan 2025-12-09 21:05", "Virtual Railfan", "https://www.youtube.com/@VirtualRailfan/streams"),
    ("xsRDTfuksyI", "Live Cam, Central Memorial Park, Calgary, Alberta 2025-12-09 21:05", "DELTATECH Calgary", "https://www.youtube.com/@DeltaTechCalgary/streams"),
    ("V_I168MM-ik", "Soggy Dollar Bar LIVE Webcam on White Bay, Jost Van Dyke, BVI 2025-12-09 21:05", "Soggy Dollar", "https://www.youtube.com/@SoggyDollar/streams"),
    ("-FguEt6H91s", "Oxford Martin School Webcam - Broad Street, Oxford 2025-12-09 21:05", "Oxford Martin School", "https://www.youtube.com/@OxfordMartinSchool/streams"),
    ("O52zDyxg5QI", "Fairbanks Aurora Camera powered by EXPLORE.org 2025-12-09 21:05", "Explore Zen Den", "https://www.youtube.com/@ExploreZenDen/streams"),
    ("L3iKvwoXZ38", "Midway Atoll NWR Wildlife Live Camera 2025-12-09 21:05", "Friends of Midway Atoll NWR", "https://www.youtube.com/@MidwayAtoll/streams"),
    ("yDKJMdZTEXQ", "VERBIER | PLACE CENTRALE 📍 2025-12-09 21:05", "Verbier", "https://www.youtube.com/@Verbier/streams"),
    ("0sK1F-jaOsE", "Chicago & North Western Power House Live Webcam (East) - Chicago, IL  #SteelHighway 2025-12-09 21:05", "Steel Highway Railcams", "https://www.youtube.com/@SteelHighway/streams"),
    ("Zot8ShPuuKg", "NORTHPORT PIER FERRY DOCK CAMERA (#1) 2025-12-09 21:05", "Michael Street", "https://www.youtube.com/@MichaelStreet/streams"),
    ("Y2VfyLoTO0c", "Steinlodge SkiCam 2025-12-09 21:05", "Stein Eriksen Lodge", "https://www.youtube.com/@SteinEriksenLodge/streams"),
    ("jtLh8BdmHUU", "Hotel East West Basel 2025-12-09 21:05", "Christian Hüttenmoser", "https://www.youtube.com/@ChristianHuttenmoser/streams"),
    ("VhVgZi2lGv0", "24/7 Live Stream 4K - Digital.Tallinn CityCam 2025-12-09 21:05", "360PANO", "https://www.youtube.com/@360PANO/streams"),
    ("J0H-rJrvzNU", "Cog Railway and Mount Washington Observatory Track Cam 2025-12-09 21:05", "Mount Washington Observatory", "https://www.youtube.com/@MountWashingtonObservatory/streams"),
    ("teGLziUvDkI", "Gatlinburg SkyPark Live Webcam 2025-12-09 21:06", "Gatlinburg SkyPark", "https://www.youtube.com/@GatlinburgSkyPark/streams"),
    ("8ySM57gHETU", "Webcam Live Val di Luce - Abetone (PT) - Piazza Centrale 2025-12-09 21:06", "Digital Landscapes", "https://www.youtube.com/@DigitalLandscapes/streams"),
    ("oylWJ-f3S5U", "🔴 Live Now: 24/7 Kilauea Volcano Livestream in Hawaii (Cam C) 2025-12-09 21:06", "afarTV", "https://www.youtube.com/@afartv/streams"),
    ("wShzNJhnBbU", "Live Cam - Pulcinella 2025-12-09 21:06", "DELTATECH Calgary", "https://www.youtube.com/@DeltaTechCalgary/streams"),
    ("xpFB6aUuFso", "Greenville Jct, Maine - Canadian Pacific Railway - Railfan Cam Live 2025-12-09 21:06", "Boston and Maine Live", "https://www.youtube.com/@BostonAndMaineLive/streams"),
    ("KdXa0xp7jLs", "EarthCam Live:  Statue of Liberty 2025-12-09 21:06", "EarthCam", "https://www.youtube.com/@earthcam/streams"),
    ("dnlQtDad6Dk", "Northern Light Live Sodankylä, Finland. North View 2025-12-09 21:06", "Starlapland / Samuli Korvanen", "https://www.youtube.com/@Starlapland/streams"),
    ("xHLEKR3_8iI", "EarthCam Live:  Coney Island (New York City) 2025-12-09 21:06", "EarthCam", "https://www.youtube.com/@earthcam/streams"),
    ("otxfXolN6Mg", "Main Street Livecam, Canmore, Alberta 2025-12-09 21:06", "CanmoreAlberta.com", "https://www.youtube.com/@CanmoreAlberta/streams"),
    ("o4fKtgPVpoU", "Dornan's in Grand Teton National Park - SeeJH.com 2025-12-09 21:06", "See Jackson Hole", "https://www.youtube.com/@SeeJacksonHole/streams"),
    ("f43H3pS3l50", "Cluj Napoca | Piata Unirii - Unirii Square | Planetarium Cafe 🔴 Live Webcam 2025-12-09 21:06", "See Transylvania", "https://www.youtube.com/@SeeTransylvania/streams"),
    ("dFBRpHHwQeg", "🔴 4K Live Webcam Venice - St. Mark's Basin in Live Streaming from Tribute to Music Venice 2025-12-09 21:06", "I Love You Venice", "https://www.youtube.com/@ILoveYouVenice/streams"),
    ("qJ8lYplu1y0", "Meteor shower & MaunaKea West view LIVE from Canada-France-Hawaii Telescope (CFHT) 2025-12-09 21:06", "Asahi Astro LIVE　朝日新聞宇宙部", "https://www.youtube.com/@AsahiAstroLIVE/streams"),
    ("UBmDO9jqrBo", "WEBCAM NEPAL LIVE – STREAMING FROM GREEN VALLEY LODGE - DZONGLA - KHUMBU - NEPAL (4830m) 2025-12-09 21:06", "WEBCAM NEPAL LIVE", "https://www.youtube.com/@WebcamNepalLive/streams"),
    ("YQIAEj9cx1s", "【富士山ライブカメラ】Mt. Fuji live camera, World heritage of JAPAN　赤富士パワーを毎日お届け。 #富士山ライブ #山中湖ライブカメラ#赤富士 #紅富士", "VICENTE AGEMATSU　(JAPAN)", "https://www.youtube.com/@VicenteAgematsu/streams"),
]

# Location data (city, country, lat, lon, placename, tags, description)
# Based on title analysis
camera_locations = {
    "86-7Dr7yeVQ": {
        "placename": "New Orleans Balcony",
        "city": "New Orleans",
        "country": "USA",
        "latitude": 29.951065,
        "longitude": -90.071533,
        "tag": "Street Scene",
        "info_0": "New Orleans balcony view",
        "des_0": "",
        "des_1": "",
    },
    "2UJDLWcSADk": {
        "placename": "Steamboat Square",
        "city": "Steamboat Springs",
        "country": "USA",
        "latitude": 40.484981,
        "longitude": -106.831757,
        "tag": "Ski Resort,Street Scene",
        "info_0": "Steamboat Resort square",
        "des_0": "",
        "des_1": "",
    },
    "XjhxRZEm638": {
        "placename": "Downtown Leavenworth",
        "city": "Leavenworth",
        "country": "USA",
        "latitude": 47.596111,
        "longitude": -120.661667,
        "tag": "Street Scene",
        "info_0": "Bavarian village downtown",
        "des_0": "",
        "des_1": "",
    },
    "dMr-Jt_K3Cc": {
        "placename": "Everett's 8800",
        "city": "Big Sky",
        "country": "USA",
        "latitude": 45.261389,
        "longitude": -111.307778,
        "tag": "Ski Resort,Mountain Range",
        "info_0": "Big Sky Resort mountain view",
        "des_0": "",
        "des_1": "",
    },
    "n49L-PpC0Wg": {
        "placename": "Docomo Tower View",
        "city": "Tokyo",
        "country": "Japan",
        "latitude": 35.689722,
        "longitude": 139.692222,
        "tag": "City Skyline",
        "info_0": "Tokyo skyline with National Stadium",
        "des_0": "",
        "des_1": "",
    },
    "9SLt3AT0rXk": {
        "placename": "La Grange Rail Crossing",
        "city": "La Grange",
        "country": "USA",
        "latitude": 38.405556,
        "longitude": -85.378889,
        "tag": "Railway",
        "info_0": "Kentucky railroad crossing",
        "des_0": "",
        "des_1": "",
    },
    "TmtVbezZaqg": {
        "placename": "Kris Kringl Shop",
        "city": "Leavenworth",
        "country": "USA",
        "latitude": 47.596389,
        "longitude": -120.661944,
        "tag": "Street Scene",
        "info_0": "Christmas shop view",
        "des_0": "",
        "des_1": "",
    },
    "YuvgiDTzxhU": {
        "placename": "San Pellegrino in Alpe",
        "city": "Garfagnana",
        "country": "Italy",
        "latitude": 44.158611,
        "longitude": 10.331111,
        "tag": "Mountain Range,Natural Scenery",
        "info_0": "Mountain village view",
        "des_0": "",
        "des_1": "",
    },
    "ahSMyLJcp48": {
        "placename": "Han River View",
        "city": "Seoul",
        "country": "South Korea",
        "latitude": 37.529722,
        "longitude": 126.933889,
        "tag": "City Skyline,Harbor",
        "info_0": "Han River and 63 Building",
        "des_0": "",
        "des_1": "",
    },
    "kC6_JqEt3GA": {
        "placename": "Main Street",
        "city": "Canmore",
        "country": "Canada",
        "latitude": 51.089444,
        "longitude": -115.357778,
        "tag": "Street Scene",
        "info_0": "Main street view",
        "des_0": "",
        "des_1": "",
    },
    "g9Y-Bkq5O0Q": {
        "placename": "Naritasan Shinshoji Temple",
        "city": "Narita",
        "country": "Japan",
        "latitude": 35.777222,
        "longitude": 140.391667,
        "tag": "Cultural Landmark",
        "info_0": "Buddhist temple view",
        "des_0": "",
        "des_1": "",
    },
    "MwcqP3ta6RI": {
        "placename": "Calgary Downtown",
        "city": "Calgary",
        "country": "Canada",
        "latitude": 51.044444,
        "longitude": -114.071667,
        "tag": "City Skyline",
        "info_0": "Calgary city view",
        "des_0": "",
        "des_1": "",
    },
    "wgkdREYOfw0": {
        "placename": "Ashland Rail Crossing",
        "city": "Ashland",
        "country": "USA",
        "latitude": 37.759444,
        "longitude": -77.479722,
        "tag": "Railway",
        "info_0": "Virginia railroad crossing",
        "des_0": "",
        "des_1": "",
    },
    "xsRDTfuksyI": {
        "placename": "Central Memorial Park",
        "city": "Calgary",
        "country": "Canada",
        "latitude": 51.043056,
        "longitude": -114.074722,
        "tag": "Natural Scenery",
        "info_0": "City park view",
        "des_0": "",
        "des_1": "",
    },
    "V_I168MM-ik": {
        "placename": "Soggy Dollar Bar",
        "city": "Jost Van Dyke",
        "country": "British Virgin Islands",
        "latitude": 18.447778,
        "longitude": -64.753333,
        "tag": "Coastline,Harbor",
        "info_0": "White Bay beach view",
        "des_0": "",
        "des_1": "",
    },
    "-FguEt6H91s": {
        "placename": "Broad Street",
        "city": "Oxford",
        "country": "United Kingdom",
        "latitude": 51.753611,
        "longitude": -1.254167,
        "tag": "Street Scene,Cultural Landmark",
        "info_0": "Historic Oxford street",
        "des_0": "",
        "des_1": "",
    },
    "O52zDyxg5QI": {
        "placename": "Fairbanks Aurora Cam",
        "city": "Fairbanks",
        "country": "USA",
        "latitude": 64.843611,
        "longitude": -147.723056,
        "tag": "Aurora,Arctic Circle",
        "info_0": "Northern lights viewing",
        "des_0": "",
        "des_1": "",
    },
    "L3iKvwoXZ38": {
        "placename": "Midway Atoll",
        "city": "Midway Atoll",
        "country": "USA",
        "latitude": 28.201389,
        "longitude": -177.377778,
        "tag": "Wildlife,Coastline",
        "info_0": "Pacific atoll wildlife",
        "des_0": "",
        "des_1": "",
    },
    "yDKJMdZTEXQ": {
        "placename": "Place Centrale",
        "city": "Verbier",
        "country": "Switzerland",
        "latitude": 46.096389,
        "longitude": 7.228333,
        "tag": "Ski Resort,Street Scene",
        "info_0": "Alpine resort center",
        "des_0": "",
        "des_1": "",
    },
    "0sK1F-jaOsE": {
        "placename": "C&NW Power House",
        "city": "Chicago",
        "country": "USA",
        "latitude": 41.878611,
        "longitude": -87.630556,
        "tag": "Railway",
        "info_0": "Railroad power house",
        "des_0": "",
        "des_1": "",
    },
    "Zot8ShPuuKg": {
        "placename": "Northport Pier",
        "city": "Northport",
        "country": "USA",
        "latitude": 45.131389,
        "longitude": -85.616944,
        "tag": "Harbor,Coastline",
        "info_0": "Ferry dock view",
        "des_0": "",
        "des_1": "",
    },
    "Y2VfyLoTO0c": {
        "placename": "Stein Eriksen Lodge",
        "city": "Park City",
        "country": "USA",
        "latitude": 40.650556,
        "longitude": -111.538889,
        "tag": "Ski Resort",
        "info_0": "Luxury ski lodge",
        "des_0": "",
        "des_1": "",
    },
    "jtLh8BdmHUU": {
        "placename": "Hotel East West",
        "city": "Basel",
        "country": "Switzerland",
        "latitude": 47.557222,
        "longitude": 7.591667,
        "tag": "Street Scene",
        "info_0": "Basel city view",
        "des_0": "",
        "des_1": "",
    },
    "VhVgZi2lGv0": {
        "placename": "Tallinn Old Town",
        "city": "Tallinn",
        "country": "Estonia",
        "latitude": 59.436944,
        "longitude": 24.745556,
        "tag": "City Skyline,Cultural Landmark",
        "info_0": "Historic city center",
        "des_0": "",
        "des_1": "",
    },
    "J0H-rJrvzNU": {
        "placename": "Mount Washington Cog Railway",
        "city": "Mount Washington",
        "country": "USA",
        "latitude": 44.270556,
        "longitude": -71.303333,
        "tag": "Railway,Mountain Range",
        "info_0": "Mountain railway track",
        "des_0": "",
        "des_1": "",
    },
    "teGLziUvDkI": {
        "placename": "Gatlinburg SkyPark",
        "city": "Gatlinburg",
        "country": "USA",
        "latitude": 35.714722,
        "longitude": -83.514167,
        "tag": "Mountain Range,Natural Scenery",
        "info_0": "Mountain overlook park",
        "des_0": "",
        "des_1": "",
    },
    "8ySM57gHETU": {
        "placename": "Val di Luce - Piazza Centrale",
        "city": "Abetone",
        "country": "Italy",
        "latitude": 44.148889,
        "longitude": 10.665556,
        "tag": "Ski Resort,Mountain Range",
        "info_0": "Mountain resort square",
        "des_0": "",
        "des_1": "",
    },
    "oylWJ-f3S5U": {
        "placename": "Kilauea Volcano",
        "city": "Hawaii Volcanoes National Park",
        "country": "USA",
        "latitude": 19.421111,
        "longitude": -155.287222,
        "tag": "Natural Scenery,Mountain Range",
        "info_0": "Active volcano view",
        "des_0": "",
        "des_1": "",
    },
    "wShzNJhnBbU": {
        "placename": "Pulcinella Restaurant",
        "city": "Calgary",
        "country": "Canada",
        "latitude": 51.045278,
        "longitude": -114.070833,
        "tag": "Street Scene",
        "info_0": "Restaurant view",
        "des_0": "",
        "des_1": "",
    },
    "xpFB6aUuFso": {
        "placename": "Greenville Junction",
        "city": "Greenville",
        "country": "USA",
        "latitude": 45.458889,
        "longitude": -69.593333,
        "tag": "Railway",
        "info_0": "Maine railway junction",
        "des_0": "",
        "des_1": "",
    },
    "KdXa0xp7jLs": {
        "placename": "Statue of Liberty",
        "city": "New York City",
        "country": "USA",
        "latitude": 40.689167,
        "longitude": -74.044444,
        "tag": "Cultural Landmark,Harbor",
        "info_0": "Liberty Island view",
        "des_0": "",
        "des_1": "",
    },
    "dnlQtDad6Dk": {
        "placename": "Sodankylä Aurora Cam",
        "city": "Sodankylä",
        "country": "Finland",
        "latitude": 67.417778,
        "longitude": 26.605556,
        "tag": "Aurora,Arctic Circle",
        "info_0": "Northern lights viewing",
        "des_0": "",
        "des_1": "",
    },
    "xHLEKR3_8iI": {
        "placename": "Coney Island",
        "city": "New York City",
        "country": "USA",
        "latitude": 40.574722,
        "longitude": -73.985833,
        "tag": "Coastline,Street Scene",
        "info_0": "Famous beach boardwalk",
        "des_0": "",
        "des_1": "",
    },
    "otxfXolN6Mg": {
        "placename": "Main Street",
        "city": "Canmore",
        "country": "Canada",
        "latitude": 51.089167,
        "longitude": -115.358056,
        "tag": "Street Scene",
        "info_0": "Downtown main street",
        "des_0": "",
        "des_1": "",
    },
    "o4fKtgPVpoU": {
        "placename": "Dornan's",
        "city": "Moose",
        "country": "USA",
        "latitude": 43.652778,
        "longitude": -110.714167,
        "tag": "Mountain Range,Natural Scenery",
        "info_0": "Grand Teton view",
        "des_0": "",
        "des_1": "",
    },
    "f43H3pS3l50": {
        "placename": "Piata Unirii",
        "city": "Cluj-Napoca",
        "country": "Romania",
        "latitude": 46.769444,
        "longitude": 23.589722,
        "tag": "Street Scene,Cultural Landmark",
        "info_0": "Historic central square",
        "des_0": "",
        "des_1": "",
    },
    "dFBRpHHwQeg": {
        "placename": "St. Mark's Basin",
        "city": "Venice",
        "country": "Italy",
        "latitude": 45.434167,
        "longitude": 12.338611,
        "tag": "Harbor,Cultural Landmark",
        "info_0": "Venice waterfront",
        "des_0": "",
        "des_1": "",
    },
    "qJ8lYplu1y0": {
        "placename": "Mauna Kea Observatory",
        "city": "Mauna Kea",
        "country": "USA",
        "latitude": 19.826389,
        "longitude": -155.478056,
        "tag": "Mountain Range,Natural Scenery",
        "info_0": "Telescope summit view",
        "des_0": "",
        "des_1": "",
    },
    "UBmDO9jqrBo": {
        "placename": "Green Valley Lodge Dzongla",
        "city": "Khumbu",
        "country": "Nepal",
        "latitude": 27.918889,
        "longitude": 86.787222,
        "tag": "Mountain Range,Natural Scenery",
        "info_0": "Himalayan trek lodge (4830m)",
        "des_0": "",
        "des_1": "",
    },
    "YQIAEj9cx1s": {
        "placename": "Lake Yamanaka View",
        "city": "Yamanakako",
        "country": "Japan",
        "latitude": 35.433333,
        "longitude": 138.866667,
        "tag": "Mountain Range,Natural Scenery",
        "info_0": "Mount Fuji view",
        "des_0": "",
        "des_1": "",
    },
}

def clean_title(title):
    """Remove date timestamp from title"""
    return re.sub(r'\s*2025-\d{2}-\d{2}\s+\d{2}:\d{2}$', '', title)

def generate_csv_rows(start_id=92):
    """Generate CSV rows for all cameras"""
    rows = []
    current_id = start_id
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3] + "+00"

    for video_id, title, channel, host_link in video_data:
        if video_id not in camera_locations:
            print(f"Warning: No location data for {video_id}")
            continue

        loc = camera_locations[video_id]
        clean_ytb_title = clean_title(title)
        link = f"https://www.youtube.com/watch?v={video_id}"

        row = {
            "camera_id": current_id,
            "link": link,
            "info_0": loc["info_0"],
            "placename": loc["placename"],
            "city": loc["city"],
            "country": loc["country"],
            "latitude": loc["latitude"],
            "longitude": loc["longitude"],
            "ytb_title": clean_ytb_title,
            "tag": loc["tag"],
            "timezone": "",
            "active": "",
            "des_0": loc["des_0"],
            "des_1": loc["des_1"],
            "sunrise_advance": 0,
            "sunset_delay": 0,
            "host_link": host_link,
            "link_available": "true",
            "last_check": current_time,
        }

        rows.append(row)
        current_id += 1

    return rows

if __name__ == "__main__":
    rows = generate_csv_rows()

    # Print CSV to stdout
    fieldnames = [
        "camera_id", "link", "info_0", "placename", "city", "country",
        "latitude", "longitude", "ytb_title", "tag", "timezone", "active",
        "des_0", "des_1", "sunrise_advance", "sunset_delay", "host_link",
        "link_available", "last_check"
    ]

    writer = csv.DictWriter(open('/Users/jia/web_app_dev/sunset-earth/new_cameras.csv', 'w'),
                           fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

    print(f"Generated {len(rows)} camera entries")
    print(f"Saved to new_cameras.csv")
