-- Migration: Populate camera_metadata for all 156 cameras
-- Created: 2025-12-18
-- Description: Bulk update all camera metadata based on manual analysis of 170 camera rules
-- Note: Cameras 33, 37, 49, 56, 65, 67, 76, 79, 83, 85, 87, 110, 118, 162 are deleted and skipped

-- ============================================================
-- STEP 1: Update all camera metadata (156 cameras)
-- ============================================================

UPDATE camera_ytb SET camera_metadata = '{"primaryType":"aurora","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":true,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 1;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":true,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":false}}'::jsonb WHERE camera_id = 2;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 3;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 4;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":true,"tier":"t3","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 5;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":false}}'::jsonb WHERE camera_id = 6;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 7;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t0","resolution":"高1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":false}}'::jsonb WHERE camera_id = 8;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t1","resolution":"高1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 9;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 10;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":true,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 11;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":true,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 12;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":true,"tier":"t0","resolution":"高1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 13;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t0","resolution":"高1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 14;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"720p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 15;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 16;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 17;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 18;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 19;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 20;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 21;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 22;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"高1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 23;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ocean","isFarpoint":true,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 24;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"aurora","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":true,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 25;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 26;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":false,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 27;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 28;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 29;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 30;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 31;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"village","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 32;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"airport","isFarpoint":true,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 34;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 35;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 36;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":true,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 38;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":true,"tier":"t1","resolution":"720p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 39;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 40;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":false,"tier":"t2","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 41;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":true,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 42;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 43;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 44;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":false,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":false}}'::jsonb WHERE camera_id = 45;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 46;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ocean","isFarpoint":true,"tier":"t1","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 47;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 48;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true},"isEventDriven":true}'::jsonb WHERE camera_id = 50;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":true,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 51;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 52;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 53;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 54;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 55;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 57;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 58;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"airport","isFarpoint":false,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 59;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"airport","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 60;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 61;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 62;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":true,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 63;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t0","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 64;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 66;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 68;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 69;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 70;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 71;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"river","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 72;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ocean","isFarpoint":false,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 73;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 74;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 75;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 77;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 78;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-view","isFarpoint":false,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":true}}'::jsonb WHERE camera_id = 80;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 81;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 82;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 84;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"village","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 86;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":true,"tier":"t1","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 88;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 89;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 90;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 91;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true},"isEventDriven":true}'::jsonb WHERE camera_id = 92;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":true,"tier":"t1","resolution":"720p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 93;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 94;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 95;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 96;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 97;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 98;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 99;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":true,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 100;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"720p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 101;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 102;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 103;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true},"isEventDriven":true}'::jsonb WHERE camera_id = 104;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 105;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 106;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":true}}'::jsonb WHERE camera_id = 107;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"aurora","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":true,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 108;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 109;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t1","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 111;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 112;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 113;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"river","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 114;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"village","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 115;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 116;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"village","isFarpoint":true,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 117;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"volcano","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":true,"lightSnow":true}}'::jsonb WHERE camera_id = 119;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 120;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 121;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"cultural-landmark","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 122;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"aurora","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":true,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 123;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":true,"tier":"t1","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 124;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t1","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 125;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 126;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 127;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":true,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 128;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":true,"tier":"t1","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 129;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 130;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 131;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 132;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t2","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 133;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":false,"anytime":true},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 134;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":false,"nightOnly":false,"noSleepTime":true,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 135;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":false,"tier":"t0","resolution":"4k","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 136;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"village","isFarpoint":false,"tier":"t1","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 137;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 138;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 139;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"skating-rink","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 140;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"skating-rink","isFarpoint":false,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 141;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"skating-rink","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 142;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 143;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 144;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ski-resort","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 145;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":true}}'::jsonb WHERE camera_id = 146;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":true,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 147;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"village","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 148;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":true,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 149;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 150;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 151;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t2","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 152;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":false,"tier":"t0","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 153;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 154;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"railway-station","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 155;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"mountain","isFarpoint":true,"tier":"t2","resolution":"720p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":true,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 156;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 157;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 158;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"beach","isFarpoint":true,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 159;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"ocean","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 160;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 161;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"skating-rink","isFarpoint":false,"tier":"t1","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 163;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"harbor","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 164;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 165;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"city-skyline","isFarpoint":true,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 166;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 167;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"nature","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 168;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"street","isFarpoint":false,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false},"isEventDriven":true}'::jsonb WHERE camera_id = 169;
UPDATE camera_ytb SET camera_metadata = '{"primaryType":"river","isFarpoint":true,"tier":"t2","resolution":"1080p","viewingTime":{"dayOnly":true,"nightOnly":false,"noSleepTime":false,"anytime":false},"weatherTolerance":{"clear":true,"partlyCloudy":false,"lightRain":false,"lightSnow":false}}'::jsonb WHERE camera_id = 170;

-- ============================================================
-- STEP 2: Verify the update
-- ============================================================

-- Count updated cameras
SELECT COUNT(*) as updated_cameras
FROM camera_ytb
WHERE camera_metadata IS NOT NULL;

-- Check distribution by primary type
SELECT
  camera_metadata->>'primaryType' as primary_type,
  COUNT(*) as count
FROM camera_ytb
WHERE camera_metadata IS NOT NULL
GROUP BY camera_metadata->>'primaryType'
ORDER BY count DESC;

-- Check farpoint distribution
SELECT
  camera_metadata->>'isFarpoint' as is_farpoint,
  COUNT(*) as count
FROM camera_ytb
WHERE camera_metadata IS NOT NULL
GROUP BY camera_metadata->>'isFarpoint';
