#!/usr/bin/env node
// Converts a camera_ytb CSV export (e.g. from the Supabase table editor) into
// SQL that D1 can execute.
//
//   node d1/csv-to-sql.mjs path/to/camera_ytb.csv > d1/seed.sql
//   npx wrangler d1 execute sunset-earth --remote --file=d1/seed.sql
//
// The CSV must have a header row. Only columns that exist in camera_ytb are
// used; unknown columns are ignored and missing ones become NULL.

import { readFileSync } from "node:fs";

const COLUMNS = [
  "camera_id",
  "link",
  "placename",
  "city",
  "country",
  "latitude",
  "longitude",
  "timezone",
  "info_0",
  "tag",
  "host_link",
  "ytb_title",
  "link_available",
  "sunset_delay",
  "sunrise_advance",
  "last_check",
  "camera_metadata",
];

const NUMERIC = new Set([
  "latitude",
  "longitude",
  "sunset_delay",
  "sunrise_advance",
]);

/** Minimal RFC-4180 CSV parser (handles quotes, escaped quotes, embedded newlines). */
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let quoted = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];

    if (quoted) {
      if (char === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else {
          quoted = false;
        }
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      quoted = true;
    } else if (char === ",") {
      row.push(field);
      field = "";
    } else if (char === "\n") {
      row.push(field);
      rows.push(row);
      row = [];
      field = "";
    } else if (char !== "\r") {
      field += char;
    }
  }

  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }

  return rows.filter((r) => r.some((cell) => cell.trim() !== ""));
}

function sqlString(value) {
  return `'${value.replace(/'/g, "''")}'`;
}

function toSqlValue(column, raw) {
  const value = raw?.trim() ?? "";

  if (value === "" || value.toLowerCase() === "null") {
    return "NULL";
  }

  if (column === "link_available") {
    const truthy = ["true", "t", "1", "yes"].includes(value.toLowerCase());
    return truthy ? "1" : "0";
  }

  if (NUMERIC.has(column)) {
    const num = Number.parseFloat(value);
    return Number.isNaN(num) ? "NULL" : String(num);
  }

  // Everything else (including camera_metadata JSON) is stored as TEXT.
  return sqlString(value);
}

const file = process.argv[2];
if (!file) {
  console.error("usage: node d1/csv-to-sql.mjs <camera_ytb.csv> > d1/seed.sql");
  process.exit(1);
}

const rows = parseCsv(readFileSync(file, "utf8"));
if (rows.length < 2) {
  console.error("error: CSV needs a header row plus at least one data row");
  process.exit(1);
}

const header = rows[0].map((h) => h.trim().replace(/^﻿/, ""));
const indexOf = new Map(header.map((name, i) => [name, i]));

const unknown = header.filter((h) => h && !COLUMNS.includes(h));
if (unknown.length) {
  console.error(`note: ignoring unknown columns: ${unknown.join(", ")}`);
}
if (!indexOf.has("camera_id")) {
  console.error("error: CSV has no camera_id column");
  process.exit(1);
}

console.log("-- Generated by d1/csv-to-sql.mjs. Safe to re-run: existing rows are replaced.");
console.log("BEGIN TRANSACTION;");

let count = 0;
for (const row of rows.slice(1)) {
  const values = COLUMNS.map((column) => {
    const index = indexOf.get(column);
    return index === undefined ? "NULL" : toSqlValue(column, row[index]);
  });

  console.log(
    `INSERT OR REPLACE INTO camera_ytb (${COLUMNS.join(", ")}) VALUES (${values.join(", ")});`
  );
  count++;
}

console.log("COMMIT;");
console.error(`ok: generated ${count} rows`);
